export enum States {
    ADD_PLAYER,
    UPDATE_PLAYER_NAME,
    READY_TO_CONNECT,
    DISCONNECT_FROM_VIDEO_CHAT,
    CONNECT_TO_COMPUTER,
    DISCONNECT_FROM_COMPUTER,
    STOP_SCREEN_SHARE,
    CONNECT_TO_WHITEBOARD,
    DISCONNECT_FROM_WHITEBOARD,
    VIDEO_CONNECTED,
    ADD_CHAT_MESSAGE,
    SEND_ROOM_DATA,
}