"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./PhaserGame";

import { ThemeProvider } from "@/components/theme-provider";
import styled from "styled-components";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const Container = styled.div`
  canvas {
    display: block;
  }
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          storageKey="n1-theme"
        >
          <Container id="phaser-container">{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
